apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata: 
  name: xbuckets.example.upbound.io
spec: 
  group: example.upbound.io
  names: 
    kind: XBucket
    plural: xbuckets
  claimNames: 
    kind: Bucket
    plural: buckets
  connectionSecretKeys:
  - arn
  versions: 
  - name: v1alpha1
    served: true
    referenceable: true
    schema: 
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties: 
              parameters: 
                description: S3 Bucket Creation Parameters
                type: object
                properties:
                  bucketName: 
                    description: S3 Bucket Name
                    type: string
                required: 
                - bucketName
          status:
            type: object
            properties: 
              bucketArn:
                description: ARN of S3 Bucket
                type: string